spring.application.name=Bt4
#Tiền tố
spring.thymeleaf.prefix=classpath:/templates/
#Hậu tố
spring.thymeleaf.suffix=.html
#Có lưu trữ tạm thời hay không
spring.thymeleaf.cache=false
server.port=8081

server.servlet.context-path=/api/v1